name: shane
favicon: null
layout_spectrum: 0.525522742420435
typography_spectrum: 0.9346543750725687
title: lockout
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.943957588635385
  lightness: 0.14058704720810056
  saturation: 0.0673534634988755
  rhythmicContrast: 0.7676928411237895
purpose: []
